### PR TITLE
Windows Install

### PR DESCRIPTION
**Pull request by Boscillator**
Temporary windows install fix.

Because windows does not support shebangs a `shellpy.py` file had to be created and installed as the script instead of just the `shellpy` file. This means `.py` files must be associated with python and that scripts must be run as `shellpy.py script.spy`.

If this update detects you are running windows it will change `shellpy` to `shellpy.py` for the scripts section of the `setup` function call in `setup.py`. It also points out the running instruction for windows in `README.md`.

### CODE REVIEW

**Comment by lamerman** [comment]
The only thing I am concerned here is that we duplicate code of the shellpy executable. Now it has the same content but in two files. If we modify it in the future we need to remember to correct it in two places. As I could see, there is a solution in setuptools to provide one script for all platforms.
https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation
So as I understand we could make it work with the original shellpy script in a way like this
`    entry_points={
        'console_scripts': [
            'shellpy = shellpy:main_func'
        ]
      }`

This does not work, there should be some error that we need to fix, maybe moving shellpy to some module and putting this module here. But in general it should be a solution. What do you think? :)

**Comment by Boscillator** [comment]
I think we get ride of `shellpy` keep `shellpy.py` then add 
```
entry_points = {
        'console_scripts': {
            'shellpy = shellpy:main'
        }
      },
```

**Comment by Boscillator** [comment]
Should I close this pull request and make a new one with the fix?

**Comment by lamerman** [comment]
@Boscillator , as I understand it does not work now. I think we could just move ```shellpy``` to ```shellpython/shellpy.py``` and in the section entry_points specify the following path ```shellpy = shellpython.shellpy:main```. I checked it should work.
Please check whether it works for you also. And yes, when you finish I think we should better commits somehow to make only one commit. Maybe just by creating a new pull request.

**Comment by lamerman** [comment]
@Boscillator please do not forget if you move ```shellpy``` to fix tests in .travis.yml

for those two lines
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./shellpy example/allinone/test.spy;  fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./shellpy example/allinone/test3.spy; fi

we need to set new relative path to shellpy. That is not ./shellpy but possibly ./shellpython/shellpy.py

**Comment by Boscillator** [comment]
ok, I'll test that. Ill create a new pull request.

**Pull request closed without merging**
